[package]

name = "rustSDLOpenGL_test"
version = "0.0.1"
authors = ["Nathan Braswell <miloignis@gmail.com>"]


[dependencies.sdl2]
git = "https://github.com/FreeFull/rust-sdl2.git"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
