[package]

name = "rustSDLOpenGL_test"
version = "0.0.1"
authors = ["Nathan Braswell <miloignis@gmail.com>"]

[dependencies]
sdl2 = "0.0.21"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2_net]
git = "https://github.com/Limvot/rust-sdl2_net"
